### ISSUE TITLE
No ffmpeg on macos.

### ISSUE THREAD

**Issue by shubhmool** [SamurAIGPT/AI-Youtube-Shorts-Generator#2]
Getting this log while running main.py
No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
Python version : 3.12.4

**Comment by Anil-matcha** [comment]
You can install ffmpeg locally on your system using homebrew

**Comment by shubhmool** [comment]
Thanks buddy. That issue was at my end only.
Closing this issue for now.
