### ISSUE TITLE
Request detected as a bot

### ISSUE THREAD

**Issue by zhanghanduo** [SamurAIGPT/AI-Youtube-Shorts-Generator#7]
I got this error: An error occurred: R9JIi2zMNHA This request was detected as a bot. Use `use_po_token=True` to view (no matter what Youtube url I input)

![image](https://github.com/user-attachments/assets/83bb9a58-2310-4e26-9730-89b0b07c71cf)

Is it the pytube package issue or my IP

**Comment by Anil-matcha** [comment]
Google is detecting your video download request as a bot. A workaround would be to download the video manually and use it locally instead of downloading using the script

**Comment by protataetuk** [comment]
How do you make it work locally without downloading the video?
